In [1]:
import numpy as np 

In [4]:
a=np.genfromtxt(r"C:\Users\Hello\Downloads\tipsf (1).csv", delimiter=",", skip_header=1)

In [5]:
a

array([[  0.  ,  16.99,   1.01, ...,   1.  ,   0.  ,   2.  ],
       [  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       ...,
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ],
       [243.  ,  18.78,   3.  , ...,   2.  ,   0.  ,   2.  ]])

In [6]:
#1)  What is the total bill value

In [7]:
np.sum(a[:,1])

4827.77

In [8]:
#2)  What is the total tip value

In [9]:
np.sum(a[:,2])

731.5799999999999

In [10]:
#3)  Count how many sun,sat,thurs,fri are there

In [11]:
day=np.unique(d[:,5],return_counts=True)
count=day[1]
print("sunday :",count[1])
print("saturday :",count[0])
print("thursday :",count[2])
print("Friday :",count[3])


sunday : 76
saturday : 87
thursday : 62
Friday : 19


In [12]:
#4)  How many smokers are there

In [14]:
np.sum(a[:,4])

93.0

In [15]:
#5)  What is the average tip given by female and male

In [16]:
a1=np.sum(a[:,2].take(np.where(a[:,3]==0)))
a2=np.sum(a[:,2].take(np.where(a[:,3]==1)))
y=np.unique(a[:,3],return_counts=True)
q,z=y
print(a1/z[0],"avg tip by female")
print(a1/z[1],"avg tip by male")

2.8334482758620685 avg tip by female
1.5701273885350315 avg tip by male


In [17]:
#6) How much amount have been spent by female and male

In [18]:
a1=np.sum(a[:,1].take(np.where(a[:,3]==0)))
a2=np.sum(a[:,1].take(np.where(a[:,3]==1)))
print("total amount spent by female: ",np.round(a1))
print("total amount spent by male: ",np.round(a2))

total amount spent by female:  1571.0
total amount spent by male:  3257.0


In [19]:
#7) what is the min and max tip given 

In [21]:
np.max(a[:,2])

10.0

In [22]:
np.min(a[:,2])

1.0

In [23]:
#8) how many male and female are going for dinner and lunch

In [24]:
a1=np.unique(a[:,3].take(np.where((a[:,6]==1))),return_counts=True)      
x,y=a1
a2=np.unique(a[:,3].take(np.where((a[:,6]==0))),return_counts=True)      
w,z=a2
for i in x:
    if(i==0):
        print("total female going for lunch",y[0])
        print("total female going for dinner",z[0])
    else:
         print("total male going for lunch",y[1])
        print("total female going for dinner",z[1])

total female going for lunch 35
total female going for dinner 52
total male going for lunch 33
total female going for dinner 124


In [25]:
#9)  find out the average size

In [26]:
np.mean(a[:7])

3.6333928571428578

In [27]:
#10) find how many female smokers and male smokers are there

In [28]:
z=np.unique(a[:,3].take(np.where((a[:,4]==1))),return_counts=True)
x,y=z
for i in x:
    if(i==0):
        print("female smokers are : ",y[0])
    else:
        print("male smokers are : ",y[1])

female smokers are :  33
male smokers are :  60


In [29]:
a=np.genfromtxt(r"C:\Users\Hello\Downloads\train_extended.csv", delimiter=",", skip_header=1)

In [30]:
a

array([[ 1.575     ,  1.225     ,  0.375     , ...,  6.3219385 ,
         9.63883   , 10.        ],
       [ 1.2375    ,  1.        ,  0.375     , ...,  3.798833  ,
         7.654365  , 19.        ],
       [ 1.45      ,  1.1625    ,  0.4125    , ...,  7.01650125,
         7.257472  , 11.        ],
       ...,
       [ 1.125     ,  0.9125    ,  0.2875    , ...,  1.984465  ,
         3.118445  ,  7.        ],
       [ 1.625     ,  1.275     ,  0.4125    , ...,  7.86698625,
        10.489315  , 11.        ],
       [ 1.5875    ,  1.25      ,  0.3875    , ...,  7.38504475,
         8.788345  , 11.        ]])

In [31]:
#1)  What is the maximum and minimum length

In [32]:
np.max(a[:,0])

7.58349125

In [33]:
np.min(a[:,0])

0.0

In [34]:
#2) Find out the difference between maximum and minimum length

In [35]:
np.max(a[:,0])-np.min(a[:,0])

7.58349125

In [36]:
#3) find column wise average.

In [37]:
def f1(x):
    return np.sum(a)/200000
np.apply_along_axis(f1,0,a)

array([57.36962797, 57.36962797, 57.36962797, 57.36962797, 57.36962797,
       57.36962797, 57.36962797, 57.36962797])

In [38]:
#4) find out all the age whose height is gereater than 0.4

In [40]:
a1=a[:,7].take(np.where(a[:,2]>0.4))
print(a.shape)
print(a)

(200000, 8)
[[ 1.575       1.225       0.375      ...  6.3219385   9.63883
  10.        ]
 [ 1.2375      1.          0.375      ...  3.798833    7.654365
  19.        ]
 [ 1.45        1.1625      0.4125     ...  7.01650125  7.257472
  11.        ]
 ...
 [ 1.125       0.9125      0.2875     ...  1.984465    3.118445
   7.        ]
 [ 1.625       1.275       0.4125     ...  7.86698625 10.489315
  11.        ]
 [ 1.5875      1.25        0.3875     ...  7.38504475  8.788345
  11.        ]]


In [41]:
#5>what is the average height and weight of the persons whose age is greater than 10.

In [42]:
print("The average height is: ",np.average(a[:,2][a[:,7]==10]))
print("The average weight is: ",np.average(a[:,3][a[:,7]==10]))

The average height is:  0.3833672856539947
The average weight is:  28.243308450511314


In [43]:
#6) what is the shell weight

In [45]:
np.sum(a[:,6])

1326845.8295214002

In [46]:
#7) how many persons belongs to each and every unique age

In [47]:
np.unique(a[:,7],return_counts=True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 29.]),
 array([   46,    42,   625,  2787,  5475, 12450, 18276, 26818, 32906,
        30803, 23457, 12717, 10037,  6352,  4831,  3191,  2705,  1953,
         1591,  1206,   721,   296,   352,   110,    51,    46,    99,
           57], dtype=int64))

In [48]:
#8) what is the difference between shucked weight and viscera weight


In [58]:
p=np.sum(a[:,4])
q=np.sum(a[:,5])
print("shuked weight and viscera weight difference = " ,p-q)

shuked weight and viscera weight difference =  999237.8582600503


In [59]:
#9) what is the average height of the persons whose age is between 14 and 19.

In [60]:
p=a.take(np.where((a[:,7]>14) & (a[:,7]<19)))
np.mean(p)
print("The average height is: ",np.average(a[:,2][a[:,7]==10]))


The average height is:  0.3833672856539947


In [61]:
#10>what is the average weight if we include all shucked weight ,viscera weight and shell weight with weight.

In [82]:
p=np.mean(np.sum(a[:,4]))
q=np.mean(np.sum(a[:,5]))
r=np.mean(np.sum(a[:,6]))

s=(p+q+r)
print("Avg weight if we include all weights = ",p+q+r)

Avg weight if we include all weights =  4323356.07048095
