In [2]:
import numpy as np

In [ ]:
#1) Write a program to create a 5 dimensional array with all zeros and ones

In [20]:
x=np.zeros((1,1,1,7,5),dtype=int)

In [21]:
x

array([[[[[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]]]]])

In [22]:
x=np.ones((1,1,1,7,5),dtype=int)

In [23]:
x

array([[[[[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]]]]])

In [ ]:
#2)  Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which create a new array of shape (3,10)



In [3]:
arr1 = np.array([[0,0,0,0,0,0,0,0,0,0],[1,1,1,1,1,1,1,1,1,1],[5,5,5,5,5,5,5,5,5,5]])
arr1
     

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [ ]:
#3)  Write a program to create a 3x4 matrix filled with values from 10 to 21.


In [32]:
y=np.arange(10,22).reshape(3,4)

In [33]:
y

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [34]:
#4)  Write a  program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9,


In [4]:
y=np.diag([0,1,2,3,4,5,6,7,8,9])

In [5]:
y

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [6]:
#5) Write a program to create a 4x4 array. Create an array from below array by swapping first and last, second and third columns.


In [8]:
x=np.array([[1,2,3,4],[2,45,7,8],[3,6,8,7],[556,77,89,8]])
x[::,::-1]

array([[  4,   3,   2,   1],
       [  8,   7,  45,   2],
       [  7,   8,   6,   3],
       [  8,  89,  77, 556]])

In [9]:
#6) Write a program to reverse an array (the first element becomes the last).
# Given array:


In [10]:
x=np.array([12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27])


In [12]:
np.flip(x,0)

array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

In [13]:
#7) Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an array of shape 10,10 .Elements range from 1 to 100


In [24]:
x=np.arange(1,101).reshape(10,10)
y=(30<x)&(80>x)&(x%5==0)
x[y]

array([35, 40, 45, 50, 55, 60, 65, 70, 75])

In [14]:
#8)Write a program to create a 2D array with 1 on the border and 0 inside.


In [4]:
x=np.array([[1,1,1,1],[1,0,0,1],[1,0,0,1],[1,1,1,1]])
x

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

In [15]:
#9) Write a program to create a checkerboard pattern .Don't use default array function
#Checkerboard pattern:                                                   
#[[0 1 0 1 0 1 0 1]                                                      
 #[1 0 1 0 1 0 1 0]                                                      
 #[0 1 0 1 0 1 0 1]                                                      
 #[1 0 1 0 1 0 1 0]                                                      
 #[0 1 0 1 0 1 0 1]                                                      
 #[1 0 1 0 1 0 1 0]     
#[0 1 0 1 0 1 0 1]                                                      
 #[1 0 1 0 1 0 1 0]]


In [6]:
z = np.arange(1,65).reshape(8,8)
x = np.arange(1,65,2)
y=np.repeat(x,2).reshape(8,8)
z-y


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [16]:
 #10)Write a program to find common values between two arrays.
#Expected Output:


In [7]:
arr1=np.array([5,7,9,11])
arr2=np.array([7,9,13,11])
set(arr2).intersection(set(arr1))

{7, 9, 11}

In [17]:
#11)Write a program to create an array 2d array and then reshape into 1d array



In [19]:
z=np.array([[1,2,3,4],[5,6,78,7],[2,4,6,3]])
z.flatten()

array([ 1,  2,  3,  4,  5,  6, 78,  7,  2,  4,  6,  3])

In [20]:
#12)Write a user defined function for creating a 1 or 2d array from scratch without using array functions


In [8]:
def ndarray(y):
    m=int(input("enter the dimension: "))
    if type(y)==list or type(y)==tuple:
        c=len(y)
    if m==1:
        print("array({})".format(y))
    elif(m==0):
        p=int(l[0])
        print("array({})".format(p))
    elif (m==2):

        if(len(y[0])>1):
            print("array([",end="")
            for i in range(c):
                print("[{}]".format(y[i]))
            print("])")
        else:
            new=[]
            for i in y:
                if (i.isdigit()):
                    z=int(i)
                    new.append(z)
            print("array([{}])".format(new))
    else:
        pass
l=[]
m=int(input("enter the range: "))
for i in range(m):
    num=input("enter the elements: ")
    l.append(num)
print(l)
ndarray(l)


enter the range: 9
enter the elements: 2
enter the elements: 3
enter the elements: 6
enter the elements: 4
enter the elements: 7
enter the elements: 1
enter the elements: 9
enter the elements: 0
enter the elements: 66
['2', '3', '6', '4', '7', '1', '9', '0', '66']
enter the dimension: 2
array([[2, 3, 6, 4, 7, 1, 9, 0, 66]])
